### ISSUE TITLE
grannyChad option crashes the program

### ISSUE THREAD

**Issue by Toma400** [Ravediff/TextLegend-python#1]
Hello! While playing the game, I've checked all options for movement, and while all told me they are "on work", grannyChad one resulted in such error:

```
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 106, in main
    title_screen()
  File "main.py", line 52, in title_screen
    title_select()
  File "main.py", line 28, in title_select
    title_screen()
  File "main.py", line 52, in title_screen
    title_select()
  File "main.py", line 15, in title_select
    intro_game()
  File "D:\TextLegend\game.py", line 89, in intro_game
    Job_classes()
  File "D:\TextLegend\game.py", line 409, in Job_classes
    Job_classes()
  File "D:\TextLegend\game.py", line 409, in Job_classes
    Job_classes()
  File "D:\TextLegend\game.py", line 409, in Job_classes
    Job_classes()
  [Previous line repeated 1 more time]
  File "D:\TextLegend\game.py", line 135, in Job_classes
    Job_classes()
  File "D:\TextLegend\game.py", line 254, in Job_classes
    story1()
  File "D:\TextLegend\game.py", line 443, in story1
    eden_town()
  File "D:\TextLegend\game.py", line 470, in eden_town
    ironWorks()
  File "D:\TextLegend\game.py", line 516, in ironWorks
    eden_town()
  File "D:\TextLegend\game.py", line 470, in eden_town
    ironWorks()
  File "D:\TextLegend\game.py", line 516, in ironWorks
    eden_town()
  File "D:\TextLegend\game.py", line 472, in eden_town
    maryInn()
  File "D:\TextLegend\game.py", line 523, in maryInn
    eden_town()
  File "D:\TextLegend\game.py", line 488, in eden_town
    eden_town()
  File "D:\TextLegend\game.py", line 468, in eden_town
    guild()
  File "D:\TextLegend\game.py", line 501, in guild
    eden_town()
  File "D:\TextLegend\game.py", line 476, in eden_town
    market()
  File "D:\TextLegend\game.py", line 509, in market
    eden_town()
  File "D:\TextLegend\game.py", line 488, in eden_town
    eden_town()
  File "D:\TextLegend\game.py", line 488, in eden_town
    eden_town()
  File "D:\TextLegend\game.py", line 488, in eden_town
    eden_town()
  [Previous line repeated 3 more times]
  File "D:\TextLegend\game.py", line 467, in eden_town
    if eden[ip.lower()] == 0:
KeyError: 'grannychad'
```

Overall, it was very simple but fun game, so thanks for two-three minutes of reading, haha <3
If you would like to collaborate (I kinda checked the game to see if I can make PR for anything), feel free to tell me! I'm open for some open source collabing ^^

**Comment by Ravediff** [comment]
Thank you very much, I would love to have your support. Actually I've been
sick for last month I haven't progressed anything.

**Comment by Ravediff** [comment]
Anyway fixed the bug, it was on the map dictionary keys. and save functions were not working so updated
. i will release a New update. if you wanna work with me i am glad

**Comment by Ravediff** [comment]
https://github.com/Ravediff/TextLegend-python/releases/tag/pre-test_0.41

**Comment by Toma400** [comment]
Thank you for reply! Glad that you are open for collab, I will fork the repo then <3
And I see you joined my Discord server! I hope you will find it cosy as well ^^
